/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anita
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        soma = new javax.swing.JButton();
        produto = new javax.swing.JButton();
        permutacao = new javax.swing.JButton();
        permutacaodepalavras = new javax.swing.JButton();
        amostragemcreposicao = new javax.swing.JButton();
        amostragemsreposição = new javax.swing.JButton();
        combinacao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SAIR = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 63, 132));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU DE OPERAÇÕES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Source Sans Pro ExtraLight", 2, 36), new java.awt.Color(240, 240, 240))); // NOI18N

        soma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soma.setForeground(new java.awt.Color(0, 0, 153));
        soma.setText("Princípio da Regra da Soma");
        soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaActionPerformed(evt);
            }
        });

        produto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        produto.setForeground(new java.awt.Color(0, 0, 153));
        produto.setText("Princípio da Regra do Produto");
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });

        permutacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        permutacao.setForeground(new java.awt.Color(0, 0, 153));
        permutacao.setText("Permutação");
        permutacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permutacaoActionPerformed(evt);
            }
        });

        permutacaodepalavras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        permutacaodepalavras.setForeground(new java.awt.Color(0, 0, 153));
        permutacaodepalavras.setText("Permutação de Letras de Uma Palavra");
        permutacaodepalavras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permutacaodepalavrasActionPerformed(evt);
            }
        });

        amostragemcreposicao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amostragemcreposicao.setForeground(new java.awt.Color(0, 0, 153));
        amostragemcreposicao.setText("Amostragem com Reposição");
        amostragemcreposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amostragemcreposicaoActionPerformed(evt);
            }
        });

        amostragemsreposição.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amostragemsreposição.setForeground(new java.awt.Color(0, 0, 153));
        amostragemsreposição.setText("Amostragem sem Reposição");
        amostragemsreposição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amostragemsreposiçãoActionPerformed(evt);
            }
        });

        combinacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combinacao.setForeground(new java.awt.Color(0, 0, 153));
        combinacao.setText("Combinações");
        combinacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combinacaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Aperte na operação que deseja realizar para ser redirecionado");

        SAIR.setBackground(new java.awt.Color(255, 255, 255));
        SAIR.setForeground(new java.awt.Color(255, 0, 0));
        SAIR.setText("SAIR");
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(permutacaodepalavras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(permutacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(amostragemsreposição, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amostragemcreposicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combinacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SAIR)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soma)
                    .addComponent(produto))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permutacao)
                    .addComponent(amostragemcreposicao))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amostragemsreposição)
                    .addComponent(combinacao))
                .addGap(60, 60, 60)
                .addComponent(permutacaodepalavras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(SAIR)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaActionPerformed
        // TODO add your handling code here:
        new principio_da_soma().setVisible(true);
    }//GEN-LAST:event_somaActionPerformed

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        // TODO add your handling code here:
        new principio_do_produto().setVisible(true);
    }//GEN-LAST:event_produtoActionPerformed

    private void permutacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permutacaoActionPerformed
        // TODO add your handling code here:
        new permutacao().setVisible(true);
    }//GEN-LAST:event_permutacaoActionPerformed

    private void permutacaodepalavrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permutacaodepalavrasActionPerformed
        // TODO add your handling code here:
        new permutacao_com_palavra().setVisible(true);
    }//GEN-LAST:event_permutacaodepalavrasActionPerformed

    private void amostragemcreposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amostragemcreposicaoActionPerformed
        // TODO add your handling code here:
        new amostragem_com_reposicao().setVisible(true);
    }//GEN-LAST:event_amostragemcreposicaoActionPerformed

    private void amostragemsreposiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amostragemsreposiçãoActionPerformed
        // TODO add your handling code here:
        new amostragem_sem_reposicao().setVisible(true);
    }//GEN-LAST:event_amostragemsreposiçãoActionPerformed

    private void combinacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combinacaoActionPerformed
        // TODO add your handling code here:
        new combinacao().setVisible(true);
    }//GEN-LAST:event_combinacaoActionPerformed

    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SAIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAIR;
    private javax.swing.JButton amostragemcreposicao;
    private javax.swing.JButton amostragemsreposição;
    private javax.swing.JButton combinacao;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton permutacao;
    private javax.swing.JButton permutacaodepalavras;
    private javax.swing.JButton produto;
    private javax.swing.JButton soma;
    // End of variables declaration//GEN-END:variables
}
